"""Project-wide constants."""

PITCH_LENGTH_M = 105.0
PITCH_WIDTH_M = 68.0
TRACKING_FPS = 25
HIGH_INTENSITY_THRESHOLD_MS = 5.5
SHARP_DECEL_THRESHOLD_MS2 = -3.0
SMOOTHING_WINDOW = 7
SMOOTHING_POLYORDER = 2

__all__ = [
    "HIGH_INTENSITY_THRESHOLD_MS",
    "PITCH_LENGTH_M",
    "PITCH_WIDTH_M",
    "SHARP_DECEL_THRESHOLD_MS2",
    "SMOOTHING_POLYORDER",
    "SMOOTHING_WINDOW",
    "TRACKING_FPS",
]
